--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#202020"
foreground="#c2c2b0"
cursor="#dc7671"

-- Colors
color0="#151515"
color1="#b44242"
color2="#95a328"
color3="#e1c135"
color4="#60928f"
color5="#7c435a"
color6="#a48b4a"
color7="#c2c2b0"
color8="#3f3639"
color9="#dc7671"
color10="#e8e85a"
color11="#9e9052"
color12="#76c39b"
color13="#86596c"
color14="#ceb34f"
color15="#b0afa8"
