# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#202020'
foreground='#c2c2b0'
cursor='#dc7671'

# Colors
color0='#151515'
color1='#b44242'
color2='#95a328'
color3='#e1c135'
color4='#60928f'
color5='#7c435a'
color6='#a48b4a'
color7='#c2c2b0'
color8='#3f3639'
color9='#dc7671'
color10='#e8e85a'
color11='#9e9052'
color12='#76c39b'
color13='#86596c'
color14='#ceb34f'
color15='#b0afa8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
