source ~/.cache/wal/colors-tty.sh
#wal -R -q
XDG_CONFIG_HOME="$HOME/.config"
export XDG_CONFIG_HOME
export PATH="$HOME/Software/bin:$HOME/Scripts:$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
export _JAVA_AWT_WM_NONREPARENTING=1
export TERM="xterm-kitty"
export XCURSOR_PATH="/usr/share/icons"
export KVM="/mnt/data/kvm"
export PG_OF_PATH="/opt/openFrameworks"

# setxkbmap -model pc104 -layout us,us -variant colemak, -option grp:shifts_toggle

# only on linux
if command -v systemctl &> /dev/null;
then
	# auto start x
	if systemctl -q is-active graphical.target && [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
	  exec Hyprland
	fi
fi
