# Environment
export PATH=$HOME/.local/bin:$PATH

export EDITOR="nvim"
export ZSH="$HOME/.oh-my-zsh"

source ~/Software/venv/bin/activate

ZSH_THEME="blinks-mag"

# Aliases
alias pip="python -m pip"
alias sht="sudo -k shutdown -h now"
alias rbt="sudo -k reboot now"
alias wttr="curl https://wttr.in/ghent"
alias vim="nvim"
alias svim="sudoedit"
alias p="ipython"
#alias ssh="try kitty +kitten ssh"
alias ssh="kitty +kitten ssh"
alias imcat="kitty +kitten icat"
alias isw="sudo isw"
alias clk="tty-clock -t -c -C 3 -B"
alias dragon="dragon-drag-and-drop"
alias o="xdg-open"
alias rep="until !!; do sleep 5 ; done"
alias nmap="grc sudo nmap"
alias cat=bat
alias python="/Users/angelo/Software/venv/bin/python3"

# Plugins
plugins=(
	docker
	git
	fzf
	colored-man-pages
#zsh-syntax-highlighting
)
fpath+=($ZSH/plugins/docker)

# Autojump
[[ -s /home/magnias/.autojump/etc/profile.d/autojump.sh ]] && source /home/magnias/.autojump/etc/profile.d/autojump.sh
autoload -U compinit && compinit -u

# Source
source $ZSH/oh-my-zsh.sh

alias ls="exa"
alias ll="exa -l"
alias l="exa -la"

# Created by `pipx` on 2024-09-16 10:07:16
export PATH="$PATH:/Users/angelo/.local/bin"
